### ISSUE TITLE
FTB Infinity Evolved integration, mobs are not spawning in world

### ISSUE THREAD

**Issue by shificz** [Rozmir-Rohi/mo-creatures-legacy#53] opened 2024-04-06 09:55 UTC
## What is the Bug?
I'm trying to add a mode to FTB Infinity Evolved 1.7.10 (3.1.0.) and in creative mode, I can spawn mobs, but in the open world (Biomes O' Plenty), mobs don't spawn freely. There's no custom mob spawning, so I see it as a bug.

## How can I Reproduce this Bug?
Examples:
Just add it to the last version of FTB Infinity Evolved

**Comment by Rozmir-Rohi** [comment] 2024-07-06 00:05
I can't seem to replicate this.
I've installed FTB Infinity Evolved v3.1 through the Curseforge app and then manually put Mo Creatures Legacy v1.1 into the Curseforge mods folder. After that I started world with the biomes o plenty option and Mo Creatures mobs were spawning correctly in the world (see pictures below).


Is it a specific biome where the mobs aren't spawning? Or maybe the mobs are spawning but in a lower amount than mobs from other mods.

![2024-07-06_09 54 21](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/120696188/2fb8c7e2-b548-48e7-9382-2351fe59f3aa)
![2024-07-06_09 59 46](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/120696188/865b98d6-8413-4720-b0da-42c4fb11a8ac)

![2024-07-06_09 36 12](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/120696188/fea218f5-4d6f-47d2-830f-c498052e9e5c)
![2024-07-06_09 53 45](https://github.com/Rozmir-Rohi/mo-creatures-legacy/assets/120696188/ebef4aed-5296-4086-890b-86b3da65fbbe)

**Comment by Rozmir-Rohi** [comment] 2024-09-03 12:00
I'm closing this issue for now since I can't reproduce this.
Please let me know if you find anything more about this.

**Closed by Rozmir-Rohi** 2024-09-03 12:00 UTC
Labels: bug, can't reproduce
